baseURL = "https://gcpdigest.com/"
languageCode = "en-us"
title = "GCP Digest"

[Params]
  description = "Handcrafted biweekly newsletter of highlights and news in Google Cloud. Not a bunch of links."